name: dayamlchecker CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    name: Run ALActions python tests
    runs-on: ubuntu-latest
    steps:
      - name: Run python tests via ALActions
        uses: SuffolkLITLab/ALActions/pythontests@main
